name: Build Todo App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Build
        run: |
          cd src
          gcc -o ../bin/todo.exe main.c todo.c gui.c utils/search.c -lgdi32 -lcomctl32 -luser32 -lole32 -luxtheme
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: todo-exe
          path: bin/todo.exe
